#!/usr/bin/env python3
"""
run_metrics.py - statistics and efficiency metrics for one run folder [BOX Lead review, 2026-09-25].

    python3 scripts/run_metrics.py runs/NY_SCH/tier2-pre/

Writes RUN_FOLDER/06-run-metrics.md and prints it. Everything is counted from the run folder itself -
nothing is estimated or typed:

  Effort       queries the operator ran (evidence files, distinct query IDs), decisions put to people
               (by role), renderer runs (rendered / refused) and the time between the first and last,
               validator result, files the operator runs to apply
  Data         rows the SQL writes, per step and per table; rows filtered out of step 7; quote refs
  Provenance   every value in values.json by where it came from: a query result, a decision, an input
  Status       walk steps by status

Standard library only. Exit 0 always (it reports; it does not judge - the validator judges).
"""
from __future__ import annotations

import csv
import datetime
import re
import subprocess
import sys
from collections import Counter
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import render_sql  # noqa: E402

STEP_TABLE = {"2": "T_BOX_ENGCONF_S", "3": "T_BOX_ENGFCURVE_S", "4": "T_BOX_ENGLKFC_X", "5": "T_BOX_ENGCONF_X",
              "6": "T_BOX_ENGACCRCONF_S", "7": "T_BOX_CONFIG_ACCRUAL_S", "11": "T_BOX_CONF_BY_BOOK_S",
              "12": "T_BOX_ERRORS_FE_S", "14a": "T_BOX_ENGDAYS_MATURED_S"}


def value_origins(obj, out: Counter) -> None:
    """Count every {value, source} leaf (and every row with a source) by the kind of source it cites."""
    if isinstance(obj, dict):
        src = obj.get("source")
        if isinstance(src, str) and ("value" in obj or any(k.isupper() for k in obj)):
            if re.search(r"decision\s+\d+", src, re.I):
                out["decided by a person (decision N)"] += 1
            elif re.search(r"\bQ-[A-Za-z0-9]", src):
                out["read from a query result (Q-...)"] += 1
            else:
                out["input or stated constant"] += 1
        for k, v in obj.items():
            if not str(k).startswith("_"):
                value_origins(v, out)
    elif isinstance(obj, list):
        for v in obj:
            value_origins(v, out)


def main(argv=None) -> int:
    argv = argv if argv is not None else sys.argv[1:]
    if not argv or not Path(argv[0]).is_dir():
        print("usage: run_metrics.py <RUN_FOLDER>", file=sys.stderr)
        return 2
    folder = Path(argv[0])
    lines = [f"# Run metrics - {folder.as_posix()}", "",
             f"Generated by `scripts/run_metrics.py` on {datetime.date.today().isoformat()}. Counted from the run "
             "folder; nothing estimated.", ""]

    # --- effort ---------------------------------------------------------------------------
    ev = sorted(p for p in (folder / "01-evidence").glob("*") if p.is_file()) if (folder / "01-evidence").is_dir() else []
    qids = sorted({m.group(0) for p in ev for m in [re.match(r"Q-[A-Za-z0-9]+", p.name)] if m})
    decisions = render_sql.read_decisions(folder / "00-decisions.md")
    roles = Counter((d.get("role") or "?").strip() for d in decisions.values())
    log = folder / "03-sql" / "render-log.csv"
    runs = list(csv.DictReader(log.open(encoding="utf-8"))) if log.exists() else []
    outcomes = Counter(r.get("outcome", "?") for r in runs)
    span = "-"
    if len(runs) >= 2:
        try:
            t0 = datetime.datetime.fromisoformat(runs[0]["timestamp_utc"])
            t1 = datetime.datetime.fromisoformat(runs[-1]["timestamp_utc"])
            span = f"{(t1 - t0).total_seconds() / 60:.0f} min"
        except (KeyError, ValueError):
            pass
    val = subprocess.run([sys.executable, str(HERE / "validate_run_output.py"), str(folder), "--quiet"],
                         capture_output=True, text=True).stdout
    vm = re.search(r"(\d+) FAIL\s+(\d+) WARN", val)
    res = render_sql.render(folder)
    sql_files = sorted(res.files) if not res.errors else []
    lines += ["## Effort", "", "| Measure | Value |", "|---|---|",
              f"| Queries run by the operator (evidence files) | {len(ev)} |",
              f"| Distinct query IDs | {len(qids)} |",
              f"| Decisions put to people (decision cards answered) | {len(decisions)} |",
              *[f"| — of which by {r} | {n} |" for r, n in sorted(roles.items())],
              f"| Renderer runs: rendered / refused / nothing to render | {outcomes.get('rendered', 0)} / "
              f"{outcomes.get('refused', 0)} / {outcomes.get('nothing', 0)} |",
              f"| Time from first to last renderer run | {span} |",
              f"| Validator now | {vm.group(1) + ' FAIL, ' + vm.group(2) + ' WARN' if vm else 'not run'} |",
              f"| Files the operator runs to apply (pre-steps + rehearsal + config + verify) | "
              f"{sum(1 for f in sql_files if 'rollback' not in f)} |", ""]

    # --- data -----------------------------------------------------------------------------
    st = res.stats if not res.errors else {}
    rows = st.get("rows_per_step", {})
    if rows:
        lines += ["## Data the SQL writes", "", "| Step | Table | Rows |", "|---|---|---|"]
        lines += [f"| {s} | `{STEP_TABLE[s]}` | {n} |" for s, n in rows.items() if s in STEP_TABLE]
        lines += [f"| **total** | {sum(1 for n in rows.values() if n)} tables | **{sum(rows.values())}** |", "",
                  f"- Quote references (step 4): {st.get('quote_refs', 0)}",
                  f"- GBO exception rows filtered out of step 7 (other branches, unapproved instruments): "
                  f"{st.get('filtered_out_step7', 0)}",
                  f"- Steps held (DRAFT if any): {', '.join(st.get('held', [])) or 'none'}", ""]
    else:
        lines += ["## Data the SQL writes", "",
                  "- Not available: values.json does not render yet"
                  + (f" ({len(res.errors)} refusal(s))." if res.errors else "."), ""]

    # --- provenance -----------------------------------------------------------------------
    vp = folder / render_sql.VALUES_FILE
    origins = Counter()
    if vp.exists():
        try:
            import json
            from decimal import Decimal
            value_origins(json.loads(vp.read_text(encoding="utf-8-sig"), parse_float=Decimal), origins)
        except Exception as e:                     # a report, not a gate
            lines += [f"- values.json unreadable: {e}", ""]
    if origins:
        total = sum(origins.values())
        lines += ["## Where the values come from", "",
                  "Entries in `values.json` (a value, or a row such as one step-6 instrument), by what their source cites:",
                  "", "| Origin | Entries | Share |", "|---|---|---|"]
        lines += [f"| {k} | {n} | {100 * n / total:.0f}% |" for k, n in origins.most_common()]
        lines += [f"| **total** | **{total}** | |", ""]
        if rows:
            lines += [f"Plus **{rows.get('4', 0) + rows.get('7', 0)} rows read straight from the evidence CSVs** "
                      "(step 4's quote references, step 7's exceptions) - never typed.", ""]

    # --- status ---------------------------------------------------------------------------
    statuses = Counter(st.get("statuses", {}).values()) if st else Counter()
    if statuses:
        lines += ["## Walk steps by status", "", "| Status | Steps |", "|---|---|"]
        lines += [f"| {k} | {n} |" for k, n in statuses.most_common()] + [""]

    text = "\n".join(lines) + "\n"
    (folder / "06-run-metrics.md").write_text(text, encoding="utf-8")
    print(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
